### ISSUE TITLE
Transaksi Pemesanan

### ISSUE THREAD

**Issue by Selfia19** [alvianingsih/Aplikasi-Laundry-BerbasisWeb#1]
Apakah pemesanan pakaian laudry sudah bisa dilakukan di dalam website?

**Comment by alvianingsih** [comment]
> Apakah pemesanan pakaian laudry sudah bisa dilakukan di dalam website?

belom bisa karena fitur buat pelanggan belum di buat,dikarenakan masih dalam tahap pengembangan

**Comment by alvianingsih** [comment]
> Apakah pemesanan pakaian laudry sudah bisa dilakukan di dalam website?

belom bisa karena fitur buat pelanggan belum di buat,dikarenakan masih dalam tahap pengembangan
